### ISSUE TITLE
Issues with dnssd v1.2.0

### ISSUE THREAD

**Issue by mrlnc** [brutella/hc#198]
Hi everybody,

I'm facing issues with commit 4da759009452b2863db09ff6b03c349103ec5bd6. I haven't found the root cause, but it seems that dnssd detects conflicts even if there are none.

* conflicts are always detected; the first name passing is with "(2)" added
* since it's adding braces, the name might become invalid for Home

https://github.com/brutella/dnssd/blob/665cf86dce8e8a8b4c6164e2ac038d6b667dc80b/probe.go#L77
https://github.com/brutella/dnssd/blob/665cf86dce8e8a8b4c6164e2ac038d6b667dc80b/probe.go#L83

I tried patching the format, but still the `.local` address is being incremented. Reverting 4da759009452b2863db09ff6b03c349103ec5bd6 works for me.

**Comment by brutella** [comment]
On which platform are you using the library?

**Comment by mrlnc** [comment]
I'm on Ubuntu Server 20.04.1, Raspberry Pi 4 (arm64).

**Comment by rblenkinsopp** [comment]
I encountered this issue running on a device with 2 interfaces to the same network. dnssd appeared to conflict with itself creating an "InstanceID (2)" entry which was unconnectable from homekit.

Disabling one of the two interfaces successfully works around the issue in my case, but it's something that should be looked at.

**Comment by brutella** [comment]
This issue should already be fixed by now.

**Comment by mrlnc** [comment]
I still encounter the same issue with the latest commit, but I could fix it like @rblenkinsopp suggested. I had two interfaces (eth and wifi) connected to the same network.

Thanks both of you.
